baseURL = 'http://blog.takumi-iida.com/'
languageCode = "ja-jp"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
title = 'Less is more'
theme = 'papermod'
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true

[minify]
    disableXML = true
    minifyOutput = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    title = "Less is more"
    description = ""
    keywords = ["Portfolio", "Blog", ]
    images = ["/images/iida_takumi_italy.jpg", ]
    DateFormat = "2006-01-02"
    defaultTheme = "auto"
    defaultThemeLight = false

    ShowReadingTime = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowShareButtons = true
    ShowWordCount = false
    ShareButtons = ["twitter", "facebook", "linkedin", "reddit", ]

    disableSpecial1stPost = false
    disableScrollToTop = false
    comments = false
    hidemeta = false
    hideSummary = true
    showtoc = false
    tocopen = false
    hideFooter = true

    [params.label]
        text = "Less is more"
        icon = "/images/steamed_rice_brown.svg"

    [params.profileMode]
        enabled = false
        title = "Takumi Iida"
        subtitle = "Computer Vision Researcher/Engineer"
        description = ""
        imageUrl = "/images/iida_takumi_italy.jpg"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/bibpile"

    [[params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/bibpile"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/takumi-iida/"
    [[params.socialIcons]]
        name = "facebook"
        url = "https://www.facebook.com/tkmiida/"
    
    [params.fuseOpts]
        isCaseSensitive = false
        shouldSort = true
        location = 0
        threshold = 0.4
        distance = 1000
        # maxPatternLength = 128
        minMatchCharLength = 0
        keys = ["title", "tags", "summary", "content", ]
    
    [params.assets]
        favicon = "/images/steamed_rice_brown.svg"
        favicon16x16 = "/images/steamed_rice_brown.svg"
        favicon32x32 = "/images/steamed_rice_brown.svg"
        apple_touch_icon = "/images/steamed_rice_brown.svg"
        safari_pinned_tab = "/images/steamed_rice_brown.svg"

[markup.goldmark.renderer]
    unsafe = true

[module]
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/bootstrap'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/simple-icons'

[languages]
    [languages.ja]
        title = "Less is more"
        weight = 1
        languageCode = "ja-jp"
        languageName = "日本語"
        contentDir = "content/ja"
    [languages.en]
        title = "Less is more"
        weight = 2
        languageCode = "en-us"
        languageName = "English"
        contentDir = "content/en"


[[languages.ja.menu.main]]
    name = "プロフィール"
    url = "aboutme"
    weight = 1

[[languages.ja.menu.main]]
    name = "記事"
    url = "posts"
    weight = 2

[[languages.ja.menu.main]]
    name = "タグ"
    url = "tags"
    weight = 3

[[languages.ja.menu.main]]
    name = "検索"
    url = "search"
    weight = 4

[[languages.ja.menu.main]]
    name = "ソート"
    url = "pubdate"
    weight = 5


[[languages.en.menu.main]]
    name = "About"
    url = "aboutme"
    weight = 1
